apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-metrics
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: metallb
  ports:
    - name: metrics
      port: 7472
      targetPort: 7472
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-speaker-metrics
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: speaker
spec:
  selector:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/name: metallb
  ports:
    - name: metrics
      port: 7472
      targetPort: 7472
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb
  namespace: metallb-system
  labels:
    app: metallb
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - metallb
  namespaceSelector:
    matchNames:
      - metallb-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
