apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: langfuse-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: langfuse-postgres-password
        property: password
    - secretKey: nextauth-secret
      remoteRef:
        key: langfuse-nextauth-secret
        property: password
    - secretKey: salt
      remoteRef:
        key: langfuse-salt
        property: password
