apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mycroft-backend
  namespace: mycroft
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-tailscale-only@kubernetescrd
spec:
  tls:
    - hosts:
        - mycroft-api.amer.dev
      secretName: mycroft-api-tls
  rules:
    - host: mycroft-api.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mycroft-backend
                port:
                  number: 8080
