apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mycroft-backend
  namespace: mycroft
  labels:
    app: mycroft-backend
spec:
  selector:
    matchLabels:
      app: mycroft-backend
  namespaceSelector:
    matchNames:
      - mycroft
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
