apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hatchet-encryption-secrets
  namespace: hatchet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: hatchet-encryption-secrets
    creationPolicy: Owner
  data:
    - secretKey: master-keyset
      remoteRef:
        key: hatchet-master-keyset
        property: password
    - secretKey: jwt-public-keyset
      remoteRef:
        key: hatchet-jwt-public-keyset
        property: password
    - secretKey: jwt-private-keyset
      remoteRef:
        key: hatchet-jwt-private-keyset
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hatchet-auth-secrets
  namespace: hatchet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: hatchet-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: cookie-secrets
      remoteRef:
        key: hatchet-cookie-secrets
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: hatchet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: hatchet-postgres-password
        property: password
