apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-poller-credentials
  namespace: unifi-poller
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: unifi-poller-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: unifi-poller-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: unifi-poller-credentials
        property: password
