apiVersion: v1
kind: Service
metadata:
  name: homeassistant-server
  namespace: mcp-homeassistant
spec:
  selector:
    app: homeassistant-server
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
