apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikimedia-db-credentials
  namespace: wikimedia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: wikimedia-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: wikimedia-postgres-password
        property: password
