apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikimedia-ingress
  namespace: wikimedia
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: wikimedia-tailscale-only@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: wiki.amer.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: infra-traefik
  tls:
    - hosts:
        - wiki.amer.dev
      secretName: wiki-amer-dev-tls
  rules:
    - host: wiki.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wikimedia
                port:
                  number: 80
