apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hatchet-api-secret
  namespace: keda
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: hatchet-api-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hatchet-worker-api-token
