apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: default
  labels:
    app: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: tcp-prometheus-servicemonitor
      path: /metrics
      interval: 60s
