apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-sql-postgres-credentials-uat
  namespace: ecdysis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: cloud-sql-postgres-credentials-uat
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dean-cloud-sql-ecdysis-uat-password
        property: password
