apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-db-credentials
  namespace: vikunja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: vikunja-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: mini-postgres-todo-password
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-jwt-secret
  namespace: vikunja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: vikunja-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: mini-vikunja-dean-jwt-secret
        property: password
