apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secure-search-mcp-secrets
  namespace: secure-search-mcp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: secure-search-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: NORDVPN_ACCESS_TOKEN
      remoteRef:
        key: nordvpn-access-token
        property: password
