apiVersion: apps/v1
kind: Deployment
metadata:
  name: phase0-test-backend-uat
  namespace: phase0-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phase0-test-backend-uat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: phase0-test-backend-uat
    spec:
      containers:
        - name: backend
          image: amerenda/phase0-test:backend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "uat"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
