apiVersion: v1
kind: Service
metadata:
  name: phase0-test-backend-uat
  namespace: phase0-test
spec:
  selector:
    app: phase0-test-backend-uat
  ports:
    - name: http
      port: 8000
      targetPort: 8000
