apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushover-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: pushover-credentials
    creationPolicy: Owner
  data:
    - secretKey: user-key
      remoteRef:
        key: pushover-user-key
        property: password
    - secretKey: token
      remoteRef:
        key: pushover-alerts-api-key
        property: password
