apiVersion: v1
kind: Service
metadata:
  name: llm-manager-backend-uat
  namespace: llm-manager
spec:
  selector:
    app: llm-manager-backend-uat
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
