apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llm-manager-frontend-uat-amer-dev-tls
  namespace: llm-manager
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretName: llm-manager-frontend-uat-amer-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - llm-manager-uat.amer.dev
  secretTemplate:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
