apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tdarr-api-key
  namespace: tdarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: tdarr-api-key
  data:
    - secretKey: TDARR_API_KEY
      remoteRef:
        key: tdarr-api-key
