apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: imggen-secrets
  namespace: imggen
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: imggen-secrets
    creationPolicy: Owner
  data:
    - secretKey: langfuse-public-key
      remoteRef:
        key: langfuse-public-key
        property: password
    - secretKey: langfuse-secret-key
      remoteRef:
        key: langfuse-secret-key
        property: password
