apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imggen-server
  namespace: imggen
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: imggen.amer.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: infra-traefik
  rules:
    - host: imggen.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: imggen-server
                port:
                  number: 8000
  tls:
    - hosts:
        - imggen.amer.dev
      secretName: imggen-amer-dev-tls
