apiVersion: v1
kind: Service
metadata:
  name: argocd-application-controller-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/component: application-controller
spec:
  selector:
    app.kubernetes.io/name: argocd-application-controller
  ports:
    - name: metrics
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: metrics
      port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/component: repo-server
spec:
  selector:
    app.kubernetes.io/name: argocd-repo-server
  ports:
    - name: metrics
      port: 8084
      targetPort: 8084
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/component: applicationset-controller
spec:
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-application-controller
  namespace: default
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server
  namespace: default
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server
  namespace: default
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-applicationset-controller
  namespace: default
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
