apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: photos-secrets
  namespace: photos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: photos-secrets
    creationPolicy: Owner
  data:
    - secretKey: github-client-id
      remoteRef:
        key: photos-github-client-id
        property: password
    - secretKey: github-client-secret
      remoteRef:
        key: photos-github-client-secret
        property: password
    - secretKey: session-secret
      remoteRef:
        key: photos-session-secret
        property: password
    - secretKey: secret-album-password
      remoteRef:
        key: photos-secret-album-password
        property: password
    - secretKey: puzzle-password
      remoteRef:
        key: photos-puzzle-password
        property: password
