apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-data
  namespace: photos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
