apiVersion: v1
kind: Service
metadata:
  name: phase16-test-backend-uat
  namespace: phase16-test
spec:
  selector:
    app: phase16-test-backend-uat
  ports:
    - name: http
      port: 8000
      targetPort: 8000
