apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: praetor-webhook-secrets
  namespace: praetor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: praetor-webhook-secrets
    creationPolicy: Owner
  data:
    - secretKey: vikunja-webhook-secret
      remoteRef:
        key: vikunja-webhook-secret
        property: password
    - secretKey: vikunja-token
      remoteRef:
        key: vikjuna-api-key-full-access
        property: password
    - secretKey: hatchet-token
      remoteRef:
        key: hatchet-worker-api-token
        property: password
    - secretKey: github-webhook-secret
      remoteRef:
        key: github-webhook-secret
        property: password
    - secretKey: praetor-api-key
      remoteRef:
        key: praetor-api-key
        property: password
    - secretKey: mem0-api-key
      remoteRef:
        key: mem0-admin-api-key
        property: password
