apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praetor-webhook-ingress
  namespace: praetor
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: praetor.amer.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: infra-traefik
  tls:
    - hosts:
        - praetor.amer.dev
      secretName: praetor-amer-dev-tls
  rules:
    - host: praetor.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: praetor-webhook-adapter
                port:
                  number: 80
