apiVersion: v1
kind: Service
metadata:
  name: external-secrets-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: infra-external-secrets
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets
  namespace: default
  labels:
    app: external-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
