apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phase0-test-ingress
  namespace: phase0-test
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: phase0-test.amer.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: infra-traefik
  tls:
    - hosts:
        - phase0-test.amer.dev
      secretName: phase0-test-amer-dev-tls
  rules:
    - host: phase0-test.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phase0-test-backend
                port:
                  number: 8000
