apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uat-postgres-credentials
  namespace: quiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: uat-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: quiz-uat-postgres-password
        property: password
