apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-prometheus-token
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: homeassistant-prometheus-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homeassistant-prometheus-token
        property: token
