apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress-amer-dev
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: homeassistant.amer.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: infra-traefik
  tls:
    - hosts:
        - homeassistant.amer.dev
      secretName: homeassistant-amer-dev-tls
  rules:
    - host: homeassistant.amer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123
