apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  namespace: home-assistant
  labels:
    app: homeassistant
    release: infra-monitoring
spec:
  selector:
    matchLabels:
      app: homeassistant
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 30s
      bearerTokenSecret:
        name: homeassistant-prometheus-token
        key: token
  namespaceSelector:
    matchNames:
      - home-assistant
