apiVersion: v1
kind: Service
metadata:
  name: kubernetes-mcp-server
  namespace: mcp-kubernetes-mcp
spec:
  selector:
    app: kubernetes-mcp-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
