apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp-secrets
  namespace: mcp-grafana-mcp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: grafana_api_key
      remoteRef:
        key: grafana-sa-mcp-user-token