apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hatchet-worker-token
  namespace: praetor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: hatchet-worker-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hatchet-worker-api-token
        property: password
