apiVersion: v1
kind: Service
metadata:
  name: arc-controller-metrics
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: gha-runner-scale-set-controller
    app.kubernetes.io/component: controller-manager
spec:
  selector:
    app.kubernetes.io/name: gha-runner-scale-set-controller
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arc-controller
  namespace: arc-systems
  labels:
    app: arc-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-runner-scale-set-controller
      app.kubernetes.io/component: controller-manager
  namespaceSelector:
    matchNames:
      - arc-systems
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
