apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
    creationPolicy: Owner
  data:
    - secretKey: llm-api-key
      remoteRef:
        key: openwebui-dean-llm-api-key
        property: password
    - secretKey: secret-key
      remoteRef:
        key: openwebui-dean-secret-key
        property: password
