apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-admin-credentials
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: openwebui-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: openwebui-dean-admin-password
        property: password
