apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libsync-redis-credentials
  namespace: libsync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: libsync-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: libsync-redis-password
        property: password
