apiVersion: v1
kind: Service
metadata:
  name: mcp-searxng-server
  namespace: mcp-searxng
spec:
  selector:
    app: mcp-searxng-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
