apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm-server
  namespace: litellm
  labels:
    app.kubernetes.io/component: litellm
spec:
  namespaceSelector:
    matchNames:
      - litellm
  selector:
    matchLabels:
      app: litellm-server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
