apiVersion: v1
kind: Service
metadata:
  name: kubernetes-ro-mcp-backend-uat
  namespace: kubernetes-ro-mcp
spec:
  selector:
    app: kubernetes-ro-mcp-backend-uat
  ports:
    - name: http
      port: 8000
      targetPort: 3000
