apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend-uat
  namespace: quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-frontend-uat
  template:
    metadata:
      labels:
        app: quiz-frontend-uat
    spec:
      containers:
        - name: frontend
          image: amerenda/quiz:frontend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
