apiVersion: v1
kind: Service
metadata:
  name: moltbook-frontend-uat
  namespace: ecdysis
spec:
  type: ClusterIP
  selector:
    app: moltbook-frontend-uat
  ports:
    - name: http
      port: 80
      targetPort: 80
