apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registration-secret
  namespace: ecdysis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: registration-secret
    creationPolicy: Owner
  data:
  - secretKey: registration-secret
    remoteRef:
      key: llm-manager-registration-secret
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
