apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycroft-bridge-worker-uat-workspace
  namespace: mycroft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
