apiVersion: v1
kind: Service
metadata:
  name: mycroft-bridge-worker-uat
  namespace: mycroft
  labels:
    app: mycroft-bridge-worker-uat
spec:
  type: ClusterIP
  selector:
    app: mycroft-bridge-worker-uat
  ports:
    - name: http
      port: 8082
      targetPort: 8082
